// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGBpikndv-qG-mknwAdbjigENHaKO-9eA',
    appId: '1:252095997769:web:de259a9fb4a46fbe7e9c98',
    messagingSenderId: '252095997769',
    projectId: 'ggnotes-lol-project',
    authDomain: 'ggnotes-lol-project.firebaseapp.com',
    storageBucket: 'ggnotes-lol-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-OKRn-yARR8uvj3IgmB1p6MsqoWCy5Xs',
    appId: '1:252095997769:android:6e7eb22e00add19f7e9c98',
    messagingSenderId: '252095997769',
    projectId: 'ggnotes-lol-project',
    storageBucket: 'ggnotes-lol-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTPww9FOfh6h6iOHGGGKxmgI0cYRkjrEA',
    appId: '1:252095997769:ios:0d193d9ed861f5ba7e9c98',
    messagingSenderId: '252095997769',
    projectId: 'ggnotes-lol-project',
    storageBucket: 'ggnotes-lol-project.appspot.com',
    iosBundleId: 'app.com.mm.teamx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTPww9FOfh6h6iOHGGGKxmgI0cYRkjrEA',
    appId: '1:252095997769:ios:0d193d9ed861f5ba7e9c98',
    messagingSenderId: '252095997769',
    projectId: 'ggnotes-lol-project',
    storageBucket: 'ggnotes-lol-project.appspot.com',
    iosBundleId: 'app.com.mm.teamx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGBpikndv-qG-mknwAdbjigENHaKO-9eA',
    appId: '1:252095997769:web:0e37821c3cb438b17e9c98',
    messagingSenderId: '252095997769',
    projectId: 'ggnotes-lol-project',
    authDomain: 'ggnotes-lol-project.firebaseapp.com',
    storageBucket: 'ggnotes-lol-project.appspot.com',
  );
}
